[tool.isort]
profile = "black"
multi_line_output = 7
py_version = 38
#single_line_exclusions = ["odoo", "odoo.exceptions", "odoo.tools", "odoo.addons"]
force_single_line = true

[tool.black]
line-length = 120
target-version = ['py38']
extend-exclude = '__init__'